export const INVENTORY_OWNER_EVENT = {
  TYPE: 'WORKFLOW_OWNER_EVENT',
  EXPIRY: 'INVENTORY_RESERVATION_EXPIRED',
  COMMITTED: 'INVENTORY_RESERVATION_COMMITTED',
  RELEASED: 'INVENTORY_RESERVATION_RELEASED',
  INVALID: 'INVENTORY_OWNER_EVENT_INVALID',
  RECOVERY_ACTION: 'REDELIVER_OWNER_EVENT',
} as const;
