export const INVENTORY_OWNER_EVENT = {
  TYPE: 'WORKFLOW_OWNER_EVENT',
  EXPIRY: 'INVENTORY_RESERVATION_EXPIRED',
  INVALID: 'INVENTORY_OWNER_EVENT_INVALID',
  RECOVERY_ACTION: 'REDELIVER_OWNER_EVENT',
} as const;
