export {
  InventoryCommandProducer,
  InventoryCommandState,
  InventoryResultDeliveryState,
} from '.prisma/inventoryClient';
export const WORKFLOW_SCHEMA_VERSION = 1;
export const WORKFLOW_INPUT_MAX_BYTES = 131072;
export const WORKFLOW_INPUT_MAX_DEPTH = 32;
export const WORKFLOW_MESSAGE = { COMMAND: 'WORKFLOW_COMMAND', RESULT: 'WORKFLOW_RESULT' } as const;
export const WORKFLOW_OUTCOME = {
  SUCCEEDED: 'SUCCEEDED',
  FAILED: 'FAILED',
  UNKNOWN: 'UNKNOWN',
} as const;
export const INVENTORY_COMMAND = {
  RESERVE: 'INVENTORY_RESERVE',
  OBSERVE: 'INVENTORY_OBSERVE',
  CLOSE_RESERVE: 'INVENTORY_CLOSE_RESERVE',
  PROTECT: 'INVENTORY_PROTECT',
  RELEASE: 'INVENTORY_RELEASE',
  COMMIT: 'INVENTORY_COMMIT',
  APPLY_RETURN: 'INVENTORY_APPLY_RETURN',
  APPLY_CANCELLATION: 'INVENTORY_APPLY_CANCELLATION',
  RESERVE_REPLACEMENT: 'INVENTORY_RESERVE_REPLACEMENT',
} as const;
export const WORKFLOW_ERROR = {
  INVALID_INPUT: 'INVALID_WORKFLOW_INPUT',
  INPUT_TOO_LARGE: 'WORKFLOW_INPUT_TOO_LARGE',
  SOURCE_MISMATCH: 'INVENTORY_COMMAND_SOURCE_MISMATCH',
  HASH_MISMATCH: 'INVENTORY_COMMAND_HASH_MISMATCH',
  ENVELOPE_CONFLICT: 'INVENTORY_COMMAND_ENVELOPE_CONFLICT',
  INBOX_CONFLICT: 'INVENTORY_INBOX_CONFLICT',
  DEADLINE_EXPIRED: 'INVENTORY_RESERVE_DEADLINE_EXPIRED',
  RECONCILIATION_REQUIRED: 'INVENTORY_COMMAND_RECONCILIATION_REQUIRED',
  DOMAIN_REJECTED: 'INVENTORY_RESERVATION_REJECTED',
  DELIVERY_CONFIGURATION: 'INVENTORY_RESULT_DELIVERY_CONFIGURATION',
  DELIVERY_UNAVAILABLE: 'INVENTORY_RESULT_DELIVERY_UNAVAILABLE',
  DELIVERY_EXHAUSTED: 'INVENTORY_RESULT_DELIVERY_EXHAUSTED',
  STALE_DELIVERY: 'INVENTORY_STALE_DELIVERY_CLAIM',
  RESULT_INVALID: 'INVENTORY_RESULT_INVALID',
} as const;
export const INVENTORY_WORKFLOW_ENV = {
  COMMERCE_COMMAND_ARN: 'COMMERCE_COMMAND_QUEUE_ARN',
  FULFILLMENT_COMMAND_ARN: 'FULFILLMENT_COMMAND_QUEUE_ARN',
  COMMERCE_RESULT_URL: 'COMMERCE_RESULT_QUEUE_URL',
  FULFILLMENT_RESULT_URL: 'FULFILLMENT_RESULT_QUEUE_URL',
} as const;
export const INVENTORY_RESULT_DELIVERY = {
  LEASE_MS: 30000,
  MAX_ATTEMPTS: 8,
  RETRY_BASE_MS: 1000,
  RETRY_MAX_MS: 300000,
  BATCH_SIZE: 20,
  BATCH_TIME_BUDGET_MS: 25000,
} as const;

export const INVENTORY_RECOVERY = {
  OWNER: 'inventory-operations',
  SEVERITY: 'HIGH',
  RECONCILE_ACTION: 'INSPECT_PAYMENT_AND_RESERVATION',
  DELIVERY_ACTION: 'REDELIVER_ORIGINAL_RESULT',
} as const;
