/** Synthetic owner event, never a substitute for provider/runtime acceptance. */
export const reservationOwnerEventFixture = (): any => ({
  type: 'WORKFLOW_OWNER_EVENT',
  schemaVersion: 1,
  producer: 'inventory',
  eventKind: 'INVENTORY_RESERVATION_EXPIRED',
  eventId: 'scope:revision:2',
  resourceType: 'checkout',
  resourceId: 'checkout',
  resourceVersion: 1,
  observedAt: '2030-01-02T00:00:00.000Z',
  expiredReservationIds: ['hold-a'],
  reservation: {
    scope: {
      id: 'scope',
      revision: 2,
      reserveOperationId: 'reserve',
      reserveOperationInputHash: 'a'.repeat(64),
      reserveInputHash: 'b'.repeat(64),
    },
    checkoutId: 'checkout',
    version: 1,
    expiresAt: '2030-01-01T00:00:00.000Z',
    lines: [
      {
        reservationId: 'hold-a',
        lineId: 'line-a',
        quantity: 1,
        revision: 1,
        state: 'EXPIRED',
        expiresAt: '2030-01-01T00:00:00.000Z',
        paymentScopeId: null,
        fence: 0,
        heldMovementId: 1,
        releasedMovementId: 2,
        soldMovementId: null,
      },
      {
        reservationId: 'hold-b',
        lineId: 'line-b',
        quantity: 1,
        revision: 0,
        state: 'HELD',
        expiresAt: '2030-01-01T00:00:00.000Z',
        paymentScopeId: null,
        fence: 0,
        heldMovementId: 3,
        releasedMovementId: null,
        soldMovementId: null,
      },
    ],
  },
});
